# **<center><span style= "color:#2F539B;">Tensors in pyTorch</span></center>**

## ***<span style= "color:purple;">Imports </span>***

In [7]:
import torch
torch.__version__, torch.cuda.is_available()

('2.6.0+cpu', False)

### ***<span style= "color:#85BB65;"> Creating a Tensor </span>***

In [8]:
# Empty function allocate a memory.
# Empty does not have any value it just asign a random location. The values that are shown are already there.
ten = torch.empty(2,3) # 2rows, 3columns
ten

tensor([[-1.5635e-02,  1.5330e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [10]:
# Cheak type
type(ten)

torch.Tensor

In [11]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# Using rand
torch.rand(2,3)

tensor([[0.1630, 0.8947, 0.4744],
        [0.1648, 0.9686, 0.1442]])

In [4]:
# Use of seed
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [6]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

### ***<span style= "color:#85BB65;"> Mathematical operation on Tensor </span>***

In [2]:
# Same as numpy
x = torch.rand(2,2)
x

tensor([[0.1976, 0.7726],
        [0.1800, 0.5641]])

In [3]:
x + 2

tensor([[2.1976, 2.7726],
        [2.1800, 2.5641]])

In [4]:
x - 2

tensor([[-1.8024, -1.2274],
        [-1.8200, -1.4359]])

In [5]:
x * 2

tensor([[0.3953, 1.5453],
        [0.3601, 1.1282]])

In [14]:
x / 2

tensor([[0.0988, 0.3863],
        [0.0900, 0.2821]])

In [9]:
a = torch.rand(2,3)
a

tensor([[0.6889, 0.5506, 0.9593],
        [0.0061, 0.0215, 0.7651]])

In [10]:
b = a.clone()

In [11]:
b[0][0] = 0

In [12]:
b

tensor([[0.0000, 0.5506, 0.9593],
        [0.0061, 0.0215, 0.7651]])

In [13]:
a

tensor([[0.6889, 0.5506, 0.9593],
        [0.0061, 0.0215, 0.7651]])