# **<center><span style= "color:#2F539B;">Training pipeline</span></center>**

## ***<span style= "color:purple;">Imports </span>***

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN


In [3]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [4]:
df.shape

(569, 31)

### ***<span style= "color:#85BB65;">Train test split </span>***

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

### ***<span style= "color:#85BB65;">Scaling </span>***

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### ***<span style= "color:#85BB65;">Label encoding </span>***

In [7]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### ***<span style= "color:#15AB75;">Numpy arrays to Pytorch tensors </span>***

In [8]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [10]:
X_train_tensor

tensor([[-0.3678,  0.0333, -0.3971,  ..., -0.8124,  0.6747, -0.3909],
        [-0.0117, -1.5060, -0.0900,  ..., -0.8884, -1.2512, -0.7359],
        [-0.4855, -1.5176, -0.5574,  ..., -1.3822, -0.9654, -0.7650],
        ...,
        [-0.3620, -0.8542, -0.3383,  ..., -0.2299, -1.4116, -0.7126],
        [-0.7641, -1.1108, -0.7593,  ..., -0.6513,  0.0841,  0.3739],
        [-1.1001, -0.7040, -1.1215,  ..., -1.4282, -0.3287, -0.5687]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

## ***<span style= "color:darkred;">Defining model </span>***

In [25]:
class mySimpleNN():
    def __init__(self, X):
        
        self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
        self.bais = torch.zeros(1, dtype=torch.float64, requires_grad=True )

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bais
        y_pred = torch.sigmoid(z)
        return y_pred
        

In [20]:
#Important Parameters
learning_rate = 0.1
epochs = 25

In [27]:
#Training Pileline

#model creation
model = mySimpleNN(X_train_tensor)

#define loop
for epoch in range (epochs):

#fowrad pass
    y_pred = model.forward(X_train_tensor)
    print(y_pred)


tensor([[2.7353e-03],
        [3.2179e-04],
        [3.0801e-05],
        [1.0000e+00],
        [3.2621e-03],
        [5.6125e-06],
        [2.2647e-03],
        [2.6155e-04],
        [9.9993e-01],
        [1.2097e-01],
        [2.8603e-02],
        [1.0384e-02],
        [7.4456e-04],
        [3.9283e-05],
        [2.8409e-04],
        [9.9995e-01],
        [9.5216e-01],
        [9.9083e-01],
        [9.9999e-01],
        [6.4494e-02],
        [5.3666e-01],
        [2.7364e-03],
        [9.9594e-01],
        [9.9155e-01],
        [3.1998e-03],
        [2.1836e-04],
        [9.9873e-01],
        [6.5633e-01],
        [1.0000e+00],
        [1.7719e-03],
        [9.9984e-01],
        [1.0000e+00],
        [1.0140e-02],
        [9.9204e-01],
        [1.0000e+00],
        [2.5209e-03],
        [9.9323e-01],
        [9.9346e-03],
        [1.1027e-02],
        [9.9253e-01],
        [2.5041e-03],
        [9.9995e-01],
        [9.9966e-01],
        [5.6668e-03],
        [5.0163e-02],
        [9

## ***<span style= "color:darkred;">Defining model with the help of NN module </span>***

#### what is nn module?
The torch.nn in PyTorch is a core library that provides a wide array of classes and fuctions desgined to help developers build neural networks.

In [28]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_featues):

        super().__init__()
        self.linear = nn.Linear(num_featues, 1)
        self.sigmoid = nn.Sigmoid()

    
    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [31]:
# Create the dataset
features = torch.rand(10,5)
features

tensor([[0.7302, 0.0818, 0.7540, 0.8236, 0.9869],
        [0.0509, 0.7019, 0.4033, 0.2911, 0.4013],
        [0.1008, 0.0560, 0.0272, 0.8410, 0.4405],
        [0.5419, 0.0242, 0.4108, 0.4047, 0.6510],
        [0.0949, 0.5370, 0.9050, 0.1484, 0.2200],
        [0.8765, 0.0062, 0.3214, 0.2962, 0.4784],
        [0.6880, 0.6221, 0.5794, 0.5547, 0.3665],
        [0.7549, 0.5120, 0.0086, 0.5850, 0.1365],
        [0.5200, 0.6928, 0.6386, 0.6604, 0.8179],
        [0.8836, 0.6852, 0.9291, 0.0036, 0.1028]])

In [32]:
#Creating the model
model = Model(features.shape[1])
# calling the model
model(features)

tensor([[0.3888],
        [0.4040],
        [0.3892],
        [0.4298],
        [0.4906],
        [0.4500],
        [0.4114],
        [0.3969],
        [0.3557],
        [0.5018]], grad_fn=<SigmoidBackward0>)

In [33]:
model.linear.weight

Parameter containing:
tensor([[-0.0021, -0.3651,  0.3413, -0.2753, -0.4462]], requires_grad=True)

In [34]:
!pip install torchinfo

In [35]:
# for visualization
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [2]:
# Neural network with hidden layer
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out



In [3]:
# dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.5802],
        [0.5812],
        [0.5845],
        [0.5788],
        [0.5828],
        [0.5808],
        [0.5744],
        [0.5815],
        [0.5799],
        [0.5842]], grad_fn=<SigmoidBackward0>)

In [4]:
from torchinfo import summary

summary(model, input_size=(10,5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [5]:
# Neural network with hidden layer
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        # updated code 
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)
        
        return out